from sqlalchemy import Column, String, DateTime, Integer, Float, Boolean, JSON, ForeignKey, Text, LargeBinary
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import uuid


class User(Base):
    """User account model."""
    __tablename__ = "users"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    username = Column(String, unique=True, nullable=False, index=True)
    display_name = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    is_active = Column(Boolean, default=True)
    
    # Relationships
    credentials = relationship("Credential", back_populates="user", cascade="all, delete-orphan")
    sessions = relationship("Session", back_populates="user", cascade="all, delete-orphan")
    baseline = relationship("UserBaseline", back_populates="user", uselist=False, cascade="all, delete-orphan")


class Credential(Base):
    """WebAuthn credential storage."""
    __tablename__ = "credentials"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    credential_id = Column(String, unique=True, nullable=False, index=True)
    public_key = Column(Text, nullable=False)
    sign_count = Column(Integer, default=0)
    transports = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_used = Column(DateTime(timezone=True), nullable=True)
    
    # Relationships
    user = relationship("User", back_populates="credentials")


class Session(Base):
    """Active user session."""
    __tablename__ = "sessions"
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    token = Column(String, unique=True, nullable=False, index=True)
    trust_score = Column(Float, default=100.0)
    status = Column(String, default="OK")  # OK, MONITOR, SUSPICIOUS, TERMINATED
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_activity = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=False)
    is_active = Column(Boolean, default=True)
    stepup_deadline = Column(DateTime(timezone=True), nullable=True)  # set when stepup required

    # Relationships
    user = relationship("User", back_populates="sessions")
    events = relationship("BehavioralEvent", back_populates="session", cascade="all, delete-orphan")
    alerts = relationship("SecurityAlert", back_populates="session", cascade="all, delete-orphan")


class SecurityAlert(Base):
    """Security alert generated by the trust engine."""
    __tablename__ = "security_alerts"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String, ForeignKey("sessions.id"), nullable=False, index=True)
    alert_type = Column(String, nullable=False)   # TRUST_DROP, STEPUP_REQUIRED, TERMINATED, STEPUP_SUCCESS
    message = Column(String, nullable=False)
    severity = Column(String, nullable=False)      # info, warning, danger
    trust_score = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    session = relationship("Session", back_populates="alerts")


class AuthChallenge(Base):
    """Temporary WebAuthn challenge storage (replaces in-memory dict).

    Rows are short-lived (TTL enforced via expires_at).  The ``username``
    column acts as a namespaced key:
      * registration  → ``"reg:<username>"``
      * login         → ``"auth:<username>"``
      * step-up       → ``"stepup:<session_id>"``
    """
    __tablename__ = "auth_challenges"

    id         = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    username   = Column(String, nullable=False, index=True)   # namespaced key
    challenge  = Column(Text, nullable=False)                 # hex-encoded bytes
    expires_at = Column(DateTime(timezone=True), nullable=False)


class UserBaseline(Base):
    """
    Stores the path to a user's personal Isolation Forest model file.
    A row is created / updated after the user completes MIN_SESSIONS_TO_TRAIN
    normal (non-terminated) sessions that together contain enough feature vectors.
    """
    __tablename__ = "user_baselines"

    id              = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id         = Column(String, ForeignKey("users.id"), nullable=False, unique=True, index=True)
    model_path      = Column(String, nullable=False)   # absolute path to .pkl file
    model_bytes     = Column(LargeBinary, nullable=True) # binary storage for stateless deployment
    sessions_used   = Column(Integer, nullable=False, default=0)  # sessions seen at training time
    vectors_used    = Column(Integer, nullable=False, default=0)  # data points used to train
    last_trained_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="baseline")
